/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'elvis' at '8/9/17 11:20 AM' with Gradle 2.12
 *
 * @author elvis, @date 8/9/17 11:20 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
